# Generated by Django 2.2.17 on 2020-12-10 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenditure', '0002_mylist2_datet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mylist2',
            name='datet',
        ),
    ]
