# Generated by Django 2.2.17 on 2020-12-10 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Income', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylist',
            name='datet',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
